### ISSUE TITLE
Buttons & Gradient

### ISSUE THREAD

**Issue by taylorsargent** [taylorsargent/dsn1674-assignment-7#1]
I cannot get the button to appear from behind the images. I also cannot figure out how to apply a gradient to the top image. @thomasjbradley

**Comment by thomasjbradley** [comment]
I can't see your website, I'm getting a 404 page.

**Comment by taylorsargent** [comment]
should be fixed now! @thomasjbradley

**Comment by thomasjbradley** [comment]
The image isn't the thing that should be `position: relative` because the button isn't _inside_ the image. Relative goes on the parent element.
